In [1]:
print('hello')

hello


In [3]:
import numpy as np

print(np.__version__)

2.5.2


In [ ]:
# ModulNotFoundError : No module named 'torch
# uv add torch torchvision
import torch

# 버전 확인
print(dir(torch))
print(torch.__version__)

# cuda 지원확인
print(torch.cuda.is_available() )


['AVG', 'AcceleratorError', 'AggregationType', 'AliasDb', 'AnyType', 'Argument', 'ArgumentSpec', 'AwaitType', 'BFloat16Storage', 'BFloat16Tensor', 'BenchmarkConfig', 'BenchmarkExecutionStats', 'Block', 'BoolStorage', 'BoolTensor', 'BoolType', 'BufferDict', 'ByteStorage', 'ByteTensor', 'CallStack', 'Capsule', 'CharStorage', 'CharTensor', 'ClassType', 'Code', 'CompilationUnit', 'CompleteArgumentSpec', 'ComplexDoubleStorage', 'ComplexFloatStorage', 'ComplexType', 'ConcreteModuleType', 'ConcreteModuleTypeBuilder', 'DeepCopyMemoTable', 'DeserializationStorageContext', 'DeviceObjType', 'DictType', 'DisableTorchFunction', 'DisableTorchFunctionSubclass', 'DispatchKey', 'DispatchKeySet', 'DoubleStorage', 'DoubleTensor', 'EnumType', 'ErrorReport', 'Event', 'ExcludeDispatchKeyGuard', 'ExecutionPlan', 'FatalError', 'FileCheck', 'FloatStorage', 'FloatTensor', 'FloatType', 'FunctionSchema', 'Future', 'FutureType', 'Generator', 'GradScaler', 'Gradient', 'Graph', 'GraphExecutorState', 'HalfStorage', '

In [8]:
import torch
import torch.nn as nn

# 1. 실행 환경에 맞는 장치(Device) 동적 할당 (표준 패턴)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("현재 사용 장치:", device)

# 2. 텐서 생성 시 처음부터 지정된 장치로 할당 (메모리 이동 오버헤드 방지)
x = torch.ones((2, 3), device=device)

# 3. 기존 텐서를 지정 장치로 이동
# Note: 텐서의 .to()는 원본을 변경하지 않고 '새로운 텐서'를 반환합니다.
y = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = y.to(device)

# 4. 신경망 모델을 지정 장치로 이동
# Note: 모델의 .to()는 모델 내부 파라미터를 'In-place(제자리)'로 이동시킵니다.
model = nn.Linear(2, 2).to(device)

# 5. 모델 연산 실행
output = model(y)
print("출력 결과 장치:", output.device)

현재 사용 장치: cpu
출력 결과 장치: cpu


# 1.1 데이터로부터 직접 생성 (From Data)

In [32]:
a = torch.tensor( [
    [1,2],
    [3,4]
])

print('dtype 지정 None : ', a)
print(type(a))
print(a.dtype)

dtype 지정 None :  tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.int64


In [36]:
# python 리스트로부터 생성
list_data = [
    [1,2,3],
    [4,5,6]
]
print('list data : ', list_data)
print( type(list_data))                             # <class 'list'>
print()


tensor_from_list = torch.tensor(list_data, dtype=torch.float32 )
print( 'List -> Tensor : ', tensor_from_list)
print( type(tensor_from_list) )                     # <class 'torch.Tensor'>
print('dtype:', tensor_from_list.dtype)
print(tensor_from_list.device)

list data :  [[1, 2, 3], [4, 5, 6]]
<class 'list'>

List -> Tensor :  tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.Tensor'>
dtype: torch.float32
cpu


In [ ]:
# numpy 배열로 부터 생성
np_array = np.array( [10,20,30] )
# np_array=[1,2,3] 는 오류남. 배열이 아니라서. 이곳이 배열이어야함. (리스트는 제공안함.)
tensor_from_np = torch.from_numpy(np_array)     # torch.tensor(np_array) 와 ,   torch.from_numpy의 차이     /       후자는 메모리를 공유한다.
# tensor_from_np = torch.tensor(np_array) 와의 차이점 !

print(f'tesor_from_np : {tensor_from_np}')
print()

tensor_from_np[0] = 999
print(f'np_array : {np_array}')
print(f'tensor_from_np : {tensor_from_np}')
print()

np_array[0] = 500
print(f'np_array : {np_array}')
print(f'tensor_from_np : {tensor_from_np}')

tesor_from_np : tensor([10, 20, 30])

np_array : [999  20  30]
tensor_from_np : tensor([999,  20,  30])

np_array : [500  20  30]
tensor_from_np : tensor([500,  20,  30])


# 1.2 특정 형태(Shape)와 값으로 초기화 (Structured Initialization)

- 이름에 like가 있는 것 : 그대로 가져옴

In [70]:
shape = (2,3)
print('zeros : \n', torch.zeros(shape) , '\n')
print('ones : \n', torch.ones(shape) ,'\n')
print('임의의 값 empty : \n', torch.empty(shape) ,'\n')
print(' 특정 값 full : \n', torch.full(shape, 3) ,'\n')

print('=======================================================================')
# 범위 기반 생성
print(torch.arange(10))    # end 값
print(torch.arange(0,10))  # start, end
print(torch.arange(0,10,2) ,'\n')      # start,end, step값


print('=======================================================================')
print('linspace:', torch.linspace(1, 10, 5) )       # (1, 10, 5) 1부터 10까지 5등분 & end값 포함
print( 'np.linspace : ', np.linspace(1,10,5, endpoint=False) )  # endpoint=True가 기본 상태

zeros : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

ones : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

임의의 값 empty : 
 tensor([[-9.4302e-41,  1.5863e-42,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00]]) 

 특정 값 full : 
 tensor([[3, 3, 3],
        [3, 3, 3]]) 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8]) 

linspace: tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
np.linspace :  [1.  2.8 4.6 6.4 8.2]


# 1.3 무작위 난수로 초기화 (Random Initialization)

In [ ]:
# 난수 생성 시 재현성을 위한 시드(seed) 값 고정
torch.manual_seed(42)

print(f'rand : {torch.rand(2,2)} \n')     # *size 는 가변.
print(f'rand : {torch.rand((2,2))} \n')

print('======randn===============')
print(f'rand : {torch.randn(2,2)} \n')

print('======randint===============')
print(f'rand : {torch.randint(10, (2,2))} \n')  #high, size=()      (low=0. 지정을 안해서)

print(f'rand : {torch.randint(1,10, (2,2))} \n') # low, high, size=()

print(f'rand : {torch.randint(low=1, high=10, size=(2,2))} \n')

print('======randperm===============')
print(f'randperm: {torch.randperm(10)}')        # 0부터 end-1까지 정수를 무작위로 섞인 1차 텐서 생성

rand : tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]]) 

rand : tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]]) 

======randn===============
rand : tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]]) 

======randint===============
rand : tensor([[5, 5],
        [7, 6]]) 

rand : tensor([[5, 9],
        [2, 6]]) 

rand : tensor([[9, 5],
        [3, 1]]) 

======randperm===============
randperm: tensor([7, 2, 6, 8, 5, 9, 0, 3, 4, 1])


# 1.4 기존 텐서의 속성을 복사하여 초기화 (_like 계열)

In [106]:
# dtype도 그대로 복사해옴 !

y = torch.tensor([
    [1,2,3],
    [4,5,6]
])

x = torch.tensor([
    [1,2,3],
    [4,5,6]
], dtype=torch.float32)


print(f'x: {x} \n')
print(f'y: {y} \n')

print(f'zeros_like : {torch.zeros_like(x)} \n')

#  shape와 dtype을 그대로 복사해옴
x_zeros = torch.zeros_like(x)
print(f'zeros_like : {x_zeros}, dtype:{x_zeros.dtype} \n')

x_ones = torch.ones_like(x)
print(f'ones_like: {x_ones}, dtype:{x_ones.dtype} \n')

x_rand = torch.rand_like(x)     # rand는 정수값을 받으면 오류남.
print(f'ones_like: {x_ones}, dtype:{x_ones.dtype} \n')

# randint_like()은 x타입이 float32이므로 그 타입을 그대로 따라서 사용이 된다.
x_randint = torch.randint_like(y, 10)
print(f'randint_like: {x_randint}, dtype:{x_randint.dtype} \n')

x: tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

y: tensor([[1, 2, 3],
        [4, 5, 6]]) 

zeros_like : tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

zeros_like : tensor([[0., 0., 0.],
        [0., 0., 0.]]), dtype:torch.float32 

ones_like: tensor([[1., 1., 1.],
        [1., 1., 1.]]), dtype:torch.float32 

ones_like: tensor([[1., 1., 1.],
        [1., 1., 1.]]), dtype:torch.float32 

randint_like: tensor([[2, 0, 8],
        [8, 7, 2]]), dtype:torch.int64 



# 1.5 텐서의 주요 속성 (Attribute)
https://docs.pytorch.org/docs/2.13/tensor_attributes.html#torch-dtype

In [117]:
# 속성을 명시하며 텐서 생성
tensor_attr = torch.ones((2,3), dtype=torch.float16, device='cpu')
                         
print('Shape(차원) : ', tensor_attr.shape)
print('Datatype (타입) : ', tensor_attr.dtype)
print('Device (장치) : ', tensor_attr.device ,'\n')

# 타입 변경 및 딥이스 이동
tensor_float32 = tensor_attr.to(dtype=torch.float32)
print('변경된 Datatype : ', tensor_float32.dtype)

# Gpu가 사용 가능한 경우 CUDA 장치로 이동
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('이동된 Device : ', device)

Shape(차원) :  torch.Size([2, 3])
Datatype (타입) :  torch.float16
Device (장치) :  cpu 

변경된 Datatype :  torch.float32
이동된 Device :  cpu


# 2. 텐서 사이즈(Tensor Szie)

## 2.1 크기 및 차원 확인 (Szie inspection)

In [123]:
print( np.shape(x) )
print( np.ndim(x) )

torch.Size([2, 3])
2


In [129]:
x = torch.arange(24). reshape(2,3,4)        # (2,3,4) 크기의 3차원 텐서.    0 ~ end-1
print(f'x : {x}')

x : tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [ ]:
print(f'size : {x.shape}')
print(f'ndim : {x.ndim}')
print(f'size : {x.size(2)}')    # x의 차원. (dim index를 넣어야함.)     size(dim)  ->  size(0) =2
print(f'numel : {x.numel() }')  # 텐서 내부의 전체 요소 갯수.

size : torch.Size([2, 3, 4])
ndim : 3
size : 4
numel : 24


## 2.2 크기 변경 및 형상 조작 (Shape Manipulation)

reshape 은 불필요한 메모리 사용 가능성
view는 이미 생성된거 사용

In [148]:
x = torch.arange(24). reshape(2,3,4)        # 3차원 텐서


# view() : 데이터가 연속적이어야함
x_view = x.view(2, 12)                      # 2차원 행렬로 변경
x_auto = x.reshape(-1,6)
print(x_view, '\n')

print(f'x_auto : {x_auto}', '\n')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]) 

x_auto : tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]) 



In [164]:
# unsqueeze & squeeze
x_2d = torch.randn(3,4)
print(f'x_2d : {x_2d}', '\n')

# unsqueezed(axis) 축을 추가할때 사용한다.  (차원확대)
x_unsqueezed = x_2d.unsqueeze(0)        # 0으로 설정하면 batch 차원 추가함. (공간 자리를 ML에서는 배치 자리라고 함.)
print(f'x_unsqueezed : {x_unsqueezed}', '\n')     # np.newaxis
print(f'x_unsqueezed : {x_unsqueezed.shape}', '\n')     # torch.size([1,3,4])

# squeeze()은 크기가 1인 차원을 찾아 없애준다. (차원축소)
x_squeeze = x_unsqueezed.squeeze(dim=0)
print(f'x_squeeze : {x_squeeze}', '\n')
print(f'x_squeeze : {x_squeeze.shape}', '\n')     # torch.Size([3,4])


# 1에 대해서만 축소

x_2d : tensor([[ 0.6027,  0.1866, -1.4744,  1.8350],
        [ 0.6578,  0.3864, -0.4322, -0.0260],
        [ 0.2864,  0.5909,  0.0679, -0.7697]]) 

x_unsqueezed : tensor([[[ 0.6027,  0.1866, -1.4744,  1.8350],
         [ 0.6578,  0.3864, -0.4322, -0.0260],
         [ 0.2864,  0.5909,  0.0679, -0.7697]]]) 

x_unsqueezed : torch.Size([1, 3, 4]) 

x_squeeze : tensor([[ 0.6027,  0.1866, -1.4744,  1.8350],
        [ 0.6578,  0.3864, -0.4322, -0.0260],
        [ 0.2864,  0.5909,  0.0679, -0.7697]]) 

x_squeeze : torch.Size([3, 4]) 



In [165]:
x_squeeze = x_unsqueezed.squeeze(dim=1)
print(f'x_squeeze : {x_squeeze}', '\n')
print(f'x_squeeze : {x_squeeze.shape}', '\n') 

x_squeeze : tensor([[[ 0.6027,  0.1866, -1.4744,  1.8350],
         [ 0.6578,  0.3864, -0.4322, -0.0260],
         [ 0.2864,  0.5909,  0.0679, -0.7697]]]) 

x_squeeze : torch.Size([1, 3, 4]) 



### Permute (차원재배치)

In [169]:
# 4. permute (차원 재배치)
img_tensor = torch.randn(32, 3, 224, 224)       # (Batch, Channel, Height, Width)
print(img_tensor.shape)
img_permuted = img_tensor.permute(0, 2, 3, 1)   # (Batch, Height, Width, channel)
print(f'img_permuted', img_permuted.shape) 

torch.Size([32, 3, 224, 224])
img_permuted torch.Size([32, 224, 224, 3])


In [177]:
# 5. expand vs repeat
a = torch.tensor([[1], 
                  [2]])      # shape : (2,1)

print(a, '\n')
print(f'expand : \n {a.expand(2,3)} \n')       # 확대

print(f'repeat : \n {a.repeat(1,4)} \n')

tensor([[1],
        [2]]) 

expand : 
 tensor([[1, 1, 1],
        [2, 2, 2]]) 

repeat : 
 tensor([[1, 1, 1, 1],
        [2, 2, 2, 2]]) 



# 3. 인덱싱, 슬라이싱 및 결합 (Indexing, Slicing &Joining)

In [ ]:
x = torch.tensor([
    [1,2,3,4,],
    [5,6,7,8],
    [9,10,11,12]
])

print(f'x : {x[1,2]}')    # 7
print(f'x : {x[1,2].item()}', '\n')

# 2. 특정 행/열 전체 추출
print('2-1. 첫번째 행 전체 (0,1) : ', x[0,1])
print('2-2. 마지막 행 전체 (:, -1) : ', x[:,-1], '\n')

# 3. 범위 슬라이싱 (0~1행, 1~2열 추출)
# [start:end]에서 end는 포함되지 않음
print('3. 부분 텐서 추출:\n', x[0:2, 1:3], '\n')

# 4.간격 지정 슬라이싱 (step=2)
print('4. 2칸 간격 추출: ', x[:,::2])



x : 7
x : 7 

2-1. 첫번째 행 전체 (0,1) :  tensor(2)
2-2. 마지막 행 전체 (:, -1) :  tensor([ 4,  8, 12]) 

3. 부분 텐서 추출:
 tensor([[2, 3],
        [6, 7]]) 

4. 2칸 간격 추출:  tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


## 3.2 고급 인덱싱 (Advanced Indexing)

In [ ]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

# 1. 불리언 마스킹 (50보다 큰 요소만 추출)
mask = x > 50
print("마스크 (Boolean Tensor):\n", mask)
print("50보다 큰 값만 추출:", x[mask])  # 1차원 텐서로 반환됨

# 2. 인덱스 리스트를 활용한 추출 (팬시 인덱싱)
# 0행과 2행 추출
rows = torch.tensor([0, 2])
print("\n0행과 2행 추출:\n", x[rows])

# 3. torch.index_select 사용 (dim=1: 열 기준 추출)
cols = torch.tensor([0, 2]) # 0열과 2열 선택
selected_cols = torch.index_select(x, dim=1, index=cols)        # dim=1 이 축의 번호를 나타내고 있음.
print("0열과 2열 추출 (index_select):\n", selected_cols)

마스크 (Boolean Tensor):
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
50보다 큰 값만 추출: tensor([60, 70, 80, 90])

0행과 2행 추출:
 tensor([[10, 20, 30],
        [70, 80, 90]])
0열과 2열 추출 (index_select):
 tensor([[10, 30],
        [40, 60],
        [70, 90]])


stack은 차원의 차수가 추가되면서 붙음

In [187]:
t1 = torch.tensor([[1, 2],
                   [3, 4]])

t2 = torch.tensor([[5, 6],
                   [7, 8]])

# 1. torch.cat (기존 차원 이어붙이기)
# dim=0: 세로 방향(행)으로 붙임
cat_dim0 = torch.cat([t1, t2], dim=0)
print("torch.cat (dim=0) Shape:", cat_dim0.shape)
print(cat_dim0)

# dim=1: 가로 방향(열)으로 붙임
cat_dim1 = torch.cat([t1, t2], dim=1)
print("\ntorch.cat (dim=1) Shape:", cat_dim1.shape)
print(cat_dim1)

# 2. torch.stack (새로운 차원 생성하며 쌓기)
# dim=0: 맨 앞에 새로운 차원 추가 (2, 2, 2)
stacked = torch.stack([t1, t2], dim=0)
print("\ntorch.stack (dim=0) Shape:", stacked.shape)
print(stacked)

torch.cat (dim=0) Shape: torch.Size([4, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

torch.cat (dim=1) Shape: torch.Size([2, 4])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

torch.stack (dim=0) Shape: torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [192]:
x = torch.randn(2, 3)
print(x)

tensor([[-1.7034,  0.9065,  0.7041],
        [ 1.2804, -1.7405, -0.3804]])


In [194]:
torch.stack((x, x), dim=0)


tensor([[[-1.7034,  0.9065,  0.7041],
         [ 1.2804, -1.7405, -0.3804]],

        [[-1.7034,  0.9065,  0.7041],
         [ 1.2804, -1.7405, -0.3804]]])

In [196]:
torch.stack((x, x), dim=1)      # 옆으로 와일드하게 추가 됨 ?

tensor([[[-1.7034,  0.9065,  0.7041],
         [-1.7034,  0.9065,  0.7041]],

        [[ 1.2804, -1.7405, -0.3804],
         [ 1.2804, -1.7405, -0.3804]]])

## 3.4 텐서 분할 (Splitting Tensors)

chunk는 갯수, split 방향

In [205]:
x = torch.arange(12).reshape(4, 3) # 4행 3열 텐서
print("분할할 원본 텐서 (4x3):\n", x)

# 1. torch.split: 행 방향(dim=0)으로 2행씩 분할
split_result = torch.split(x, split_size_or_sections=1, dim=0)      # 4로 하면 안 나눠짐. split은 몇ㅗ=행씩 나눠야함.  <>  chunk는 몇 등분
print("\nsplit (크기 2씩 분할 결과):")
for t in split_result:
    print(t)

# 2. torch.chunk: 행 방향(dim=0)으로 총 2개의 덩어리로 분할
chunk_result = torch.chunk(x, chunks=4, dim=0)
print("\nchunk (2개로 등분 결과):")
for t in chunk_result:
    print(t)

분할할 원본 텐서 (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

split (크기 2씩 분할 결과):
tensor([[0, 1, 2]])
tensor([[3, 4, 5]])
tensor([[6, 7, 8]])
tensor([[ 9, 10, 11]])

chunk (2개로 등분 결과):
tensor([[0, 1, 2]])
tensor([[3, 4, 5]])
tensor([[6, 7, 8]])
tensor([[ 9, 10, 11]])


In [203]:
x = torch.arange(12).reshape(4, 3) # 4행 3열 텐서
print("분할할 원본 텐서 (4x3):\n", x)

# 1. torch.split: 행 방향(dim=0)으로 2행씩 분할
split_result = torch.split(x, split_size_or_sections=2, dim=0)
print("\nsplit (크기 2씩 분할 결과):")
for t in split_result:
    print(t)

# 2. torch.chunk: 행 방향(dim=0)으로 총 2개의 덩어리로 분할
chunk_result = torch.chunk(x, chunks=2, dim=0)
print("\nchunk (2개로 등분 결과):")
for t in chunk_result:
    print(t)

분할할 원본 텐서 (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

split (크기 2씩 분할 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

chunk (2개로 등분 결과):
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


4.3 데이터 타입 지정 및 형변환 (Type Casting)

In [206]:
# 1. 생성 시 dtype 명시
x_float16 = torch.tensor([1.5, 2.5], dtype=torch.float16)
x_int32 = torch.zeros((2, 2), dtype=torch.int32)

# 2. 형변환 방식 1: .to() 메서드 (권장 표준 패턴)
# 디바이스(CPU/GPU) 변경과 dtype 변경을 동시에 수행할 수 있어 가장 많이 쓰입니다.
x_converted = x_float16.to(torch.float32)
print("to() 변환 후:", x_converted.dtype)

# 3. 형변환 방식 2: 축약 메서드 (.float(), .long(), .bool() 등)
x_long = x_float16.long()   # float16 -> int64 (소수점 버림 처리)
x_bool = x_float16.bool()   # 0이 아니면 True
print("long() 변환 후 (값):", x_long)
print("bool() 변환 후 (값):", x_bool)

# 4. 형변환 방식 3: 다른 텐서의 dtype 추종 (.type_as())
target_tensor = torch.ones(2, dtype=torch.float64)
x_matched = x_float16.type_as(target_tensor)
print("type_as() 변환 후:", x_matched.dtype)

to() 변환 후: torch.float32
long() 변환 후 (값): tensor([1, 2])
bool() 변환 후 (값): tensor([True, True])
type_as() 변환 후: torch.float64


## 4.4 자동 형변환 및 승격 (Type Promotion)

In [207]:
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([0.5, 1.5, 2.5], dtype=torch.float32)

# int32 + float32 -> float32로 자동 승격
result = int_tensor + float_tensor
print("연산 결과:", result)
print("자동 승격된 dtype:", result.dtype) # torch.float32

연산 결과: tensor([1.5000, 3.5000, 5.5000])
자동 승격된 dtype: torch.float32


### 양자화 : 자료형이 변경됨

양자화(Quantization)는 쉽게 말해 "소수점까지 정밀하고 긴 숫자를, 가볍고 딱딱 떨어지는 숫자(정수)로 반올림해서 줄이는 기술"입니다.

## 6.3 집계 연산 (Reduction Operations)

In [209]:
x = torch.tensor([[1.0, 5.0, 3.0],
                  [4.0, 2.0, 6.0]]) # Shape: (2, 3)

# 1. 전체 요소 집계
print("전체 합:", x.sum().item())
print("전체 평균:", x.mean().item())

# 2. 차원(dim) 기준 집계
# dim=0: 행 방향(세로)으로 뭉쳐서 연산 -> 결과 Shape: (3,)
print("\n행 기준(dim=0) 평균:", x.mean(dim=0))

# dim=1: 열 방향(가로)으로 뭉쳐서 연산 -> 결과 Shape: (2,)
print("행 기준(dim=1) 최댓값:", x.max(dim=1).values)

# 3. keepdim=True 옵션
sum_keepdim = x.sum(dim=1, keepdim=True)
print("\nkeepdim=True 적용 합 Shape:", sum_keepdim.shape) # (2, 1)

# 4. Argmax (최댓값의 인덱스 위치)
print("\n행 기준 가장 큰 값의 인덱스 (dim=1):", x.argmax(dim=1)) # [1, 2]

전체 합: 21.0
전체 평균: 3.5

행 기준(dim=0) 평균: tensor([2.5000, 3.5000, 4.5000])
행 기준(dim=1) 최댓값: tensor([5., 6.])

keepdim=True 적용 합 Shape: torch.Size([2, 1])

행 기준 가장 큰 값의 인덱스 (dim=1): tensor([1, 2])


## 6.4 제자리 연산 (In-place Operations)

In [211]:
x = torch.tensor([1.0, 2.0, 3.0])
print("초기 메모리 주소:", id(x))

# Out-of-place 연산 (새로운 텐서 생성 -> 주소 변경됨)
x_new = x + 5.0
print("Out-of-place 후 x 주소:", id(x))
print("n_new 주소:", id(x_new))

# In-place 연산 (기존 텐서 메모리에 즉시 반영 -> 주소 동일)
x.add_(5.0)
print("In-place 연산 후 x 값:", x)
print("In-place 후 x 주소:", id(x)) # 초기 주소와 동일함

# 모든 요소를 0으로 초기화
x.zero_()
print("zero_() 적용 후:", x)

초기 메모리 주소: 1999639141408
Out-of-place 후 x 주소: 1999639141408
n_new 주소: 1999637449376
In-place 연산 후 x 값: tensor([6., 7., 8.])
In-place 후 x 주소: 1999639141408
zero_() 적용 후: tensor([0., 0., 0.])
